# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUIQydCsN.ui'
##
## Created by: Qt User Interface Compiler version 6.0.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(394, 300)
        MainWindow.setBaseSize(QSize(0, 0))
        MainWindow.setAnimated(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 121, 31))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamily(u"Sitka Banner")
        font.setPointSize(15)
        self.label.setFont(font)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(150, 0, 10, 300))
        self.line.setFrameShadow(QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(10)
        self.line.setFrameShape(QFrame.VLine)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(0, 30, 71, 24))
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 110, 155, 20))
        self.line_2.setFrameShadow(QFrame.Plain)
        self.line_2.setLineWidth(5)
        self.line_2.setMidLineWidth(37)
        self.line_2.setFrameShape(QFrame.HLine)
        self.Temp = QLCDNumber(self.centralwidget)
        self.Temp.setObjectName(u"Temp")
        self.Temp.setGeometry(QRect(80, 40, 61, 71))
        self.Temp.setDigitCount(4)
        self.Temp.setProperty("value", 97.299999999999997)
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(0, 60, 71, 24))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(0, 90, 71, 24))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(120, 0, 21, 31))
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 130, 121, 31))
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setFont(font)
        self.Temp_2 = QLCDNumber(self.centralwidget)
        self.Temp_2.setObjectName(u"Temp_2")
        self.Temp_2.setGeometry(QRect(80, 160, 61, 31))
        self.Temp_2.setDigitCount(4)
        self.Temp_2.setProperty("value", 97.299999999999997)
        self.Temp_3 = QLCDNumber(self.centralwidget)
        self.Temp_3.setObjectName(u"Temp_3")
        self.Temp_3.setGeometry(QRect(80, 200, 61, 31))
        self.Temp_3.setDigitCount(4)
        self.Temp_3.setProperty("value", 97.299999999999997)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 170, 49, 16))
        font1 = QFont()
        font1.setFamily(u"Sitka Heading")
        font1.setPointSize(10)
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 210, 49, 16))
        self.label_5.setFont(font1)
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(0, 240, 61, 24))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(80, 240, 61, 24))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(160, 0, 121, 31))
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setFont(font)
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(160, 60, 231, 111))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(280, 180, 61, 24))
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(200, 180, 61, 24))
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(156, 210, 250, 20))
        self.line_3.setFrameShadow(QFrame.Plain)
        self.line_3.setLineWidth(5)
        self.line_3.setMidLineWidth(37)
        self.line_3.setFrameShape(QFrame.HLine)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(160, 230, 121, 21))
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setFont(font)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(280, 230, 91, 61))
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setFamily(u"Sitka Banner")
        font2.setPointSize(25)
        self.label_8.setFont(font2)
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(160, 260, 91, 24))
        self.Temp_4 = QLCDNumber(self.centralwidget)
        self.Temp_4.setObjectName(u"Temp_4")
        self.Temp_4.setGeometry(QRect(330, 0, 61, 61))
        self.Temp_4.setDigitCount(4)
        self.Temp_4.setProperty("value", 97.299999999999997)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(210, 30, 121, 21))
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font3 = QFont()
        font3.setFamily(u"Sitka Banner")
        font3.setPointSize(12)
        self.label_9.setFont(font3)
        MainWindow.setCentralWidget(self.centralwidget)
#if QT_CONFIG(shortcut)
        self.label.setBuddy(self.label)
        self.label_2.setBuddy(self.label)
        self.label_3.setBuddy(self.label)
        self.label_6.setBuddy(self.label)
        self.label_7.setBuddy(self.label)
        self.label_8.setBuddy(self.label)
        self.label_9.setBuddy(self.label)
#endif // QT_CONFIG(shortcut)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Febris", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Temperature", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Celcius", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Fahernheit", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"(F)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Blood Pressure", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Systolic", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Diastolic", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"ECG", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Device Status:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"good", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Export Data", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Heart Rate (BPM):", None))
    # retranslateUi

